Ürün Stok Takip Bitirme Projesi/Controllers/GuvenlikController.cs
using Ürün_Stok_Takip_Bitirme_Projesi.Models.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Web;
using System.Web.Security;

namespace Ürün_Stok_Takip_Bitirme_Projesi.Controllers
{
    public class GuvenlikController : Controller
    {
        dbStokMVCEntities3 db = new dbStokMVCEntities3();

        public ActionResult GirisYap()
        {
            return View();
        }

        public enum AlertEnum
        {
            danger,
        }

        [HttpPost]
        public ActionResult GirisYap(TBKULLANCILAR t)
        {
            var bilgiler = db.TBKULLANCILAR.FirstOrDefault(x => x.AD == t.AD && x.SIFRA == t.SIFRA);
            if (bilgiler != null)
            {
             
                Session["bilgiler"] = bilgiler.ID;

                Response.Cache.SetCacheability(HttpCacheability.NoCache);
                Response.Cache.SetNoStore();

                return RedirectToAction("Anasayfa", "Default");
            }
            else
            {
                ViewBag.Mesaj = "Kullanıcı adı veya şifre hatalı";
                ViewBag.AlertEnum = AlertEnum.danger;
                return View();
            }
        }

        public ActionResult CikisYap()
        {
            if (Session["bilgiler"] != null)
            {
                Session.Remove("bilgiler");
            }
            Session.Abandon();
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetNoStore();
            return RedirectToAction("GirisYap");
        }
    }
}

Ürün Stok Takip Bitirme Projesi/Views/Guvenlik/GirisYap.cshtml
@model Ürün_Stok_Takip_Bitirme_Projesi.Models.Entity.TBKULLANCILAR

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Giriş Sayfası</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Login_v1/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login_v1/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Login_v1/css/main.css">
    <!--===============================================================================================-->
</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="~/Login_v1/images/img-01.png" alt="IMG">
                </div>
                @using (Html.BeginForm("GirisYap", "Guvenlik", FormMethod.Post, new { @class = "login100-form validate-form" }))
                {
                    <span class="login100-form-title">
                        Hesabınız Giriş Yap
                    </span>

                    <div class="wrap-input100 validate-input" data-validate="Geçerli e-posta gerekli: ex@abc.xyz">
                        <input class="input100" type="text" name="AD" placeholder="Email Adresi">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Şifre gereklidir">
                        <input class="input100" type="password" name="SIFRA" placeholder="Şifreniz">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Giriş Yap
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>

    <!--===============================================================================================-->
    <script src="~/Login_v1/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v1/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Login_v1/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v1/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v1/vendor/tilt/tilt.jquery.min.js"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="~/Login_v1/js/main.js"></script>
</body>
</html>